### ISSUE TITLE
Fix a bug? 

### ISSUE THREAD

**Issue by sebastianjnuwu** [legendSabbir/acode-editorTheme-template#2]
Hello, I made a plugin according to your template, upgrading the code to add more than one theme to the array, thus having multiple themes. Unfortunately I have an annoying bug when I close and open acode the theme disappears

**Comment by sebastianjnuwu** [comment]
repo: https://github.com/sebastianjnuwu/acode-plugins/tree/theme-editor

**Comment by sebastianjnuwu** [comment]
Maybe the bug is here, I don't know: https://github.com/sebastianjnuwu/acode-plugins/blob/9a9f4b5df9bdd4a77f0b00bd73ec632461551324/src/main.js#L38

**Comment by sebastianjnuwu** [comment]
I'm going to sleep here it's dawn

**Comment by legend-sabbir** [comment]
delete
```javascript
const current = settings.get('editorTheme');
	if (current === name) {
		 editor.setTheme(`ace/theme/${name}`);
	   settings.update({ editorTheme: name });
	};
```

and add the following code after the foreach loop

```javascript
const current = settings.get('editorTheme');
    const themeIndex = theme.indexOf(current)
    if (hasTheme > -1) {
      editor.setTheme(`ace/theme/${theme[themeIndex]}`);
      settings.update({ editorTheme: theme[themeIndex] });
    }; 
```

**Comment by legend-sabbir** [comment]
https://github.com/legendSabbir/acode-editorTheme-template/blob/master/src/main.js#L41

it because you deleted this code .

**Comment by sebastianjnuwu** [comment]
> https://github.com/legendSabbir/acode-editorTheme-template/blob/master/src/main.js#L41
> 
> it because you deleted this code .

ahhh, I put this in the if thinking it would solve it actually I didn't understand the logic very well, 

based on what you said, I put the update ecento but it's still not working maybe it's the way I'm putting it can you check?

```js 
const theme = ['Night-Owl', 'Github-Dark'];

// .....
 async init() {
  theme.forEach(name => {
   // ...
   const current = settings.get('editorTheme');
  	if (current === name) {
		 editor.setTheme(`ace/theme/${name}`);
     settings.on('update', this.change(name))
	};
 });
 }
 
 async change(value) {
    if (theme.includes(value)) {
      editor.setTheme(`ace/theme/${value}`);
      settings.update({ editorTheme: value });
    }
  };
 // ...
```

looking like this is there any error? like i said it's still not working

**Comment by legend-sabbir** [comment]
it will not work , because you deleted the logic for this exact purpose
https://github.com/legendSabbir/acode-editorTheme-template/blob/master/src/main.js#L41

**Comment by legend-sabbir** [comment]
also theme name wasnt meant to be passed by an array so some logic needs to be changed

**Comment by legend-sabbir** [comment]
any your code is also not valid

**Comment by sebastianjnuwu** [comment]
> também o nome do tema não deveria ser passado por uma matriz, então alguma lógica precisa ser alterada

Any idea? It uses `forEach` to have multiple themes, I DON'T know which logic to apply to solve

**Comment by legend-sabbir** [comment]
for that i have to test , i will reply after checking it

**Comment by sebastianjnuwu** [comment]
> for that i have to test , i will reply after checking it

ok

**Comment by legend-sabbir** [comment]
```javascript
import plugin from '../plugin.json';
import style from "./style.scss";
const settings = acode.require('settings');
const { editor } = editorManager

const themes = ["hello", "world"]

class AcodePlugin {
  async init() {
    const themeList = ace.require("ace/ext/themelist")
    const currentTheme = settings.get("editorTheme")
    
    themes.forEach(name => {
      themeList.themes.push({
        caption: name.split("-").map(n => n[0].toUpperCase() + n.slice(1)).join(" "),
        theme: "ace/theme/" + name,
        isDark: true
      });
      
      ace.define(`ace/theme/${name}.css`, ["require", "exports", "module"], function (require, exports, module) { module.exports = style }),
      ace.define(`ace/theme/${name}`, ["require", "exports", "module", `ace/theme/${name}.css`, "ace/lib/dom"], function (require, exports, module) {
        exports.isDark = !0,
        exports.cssClass = `ace-${name}`,
        exports.cssText = require(`./${name}.css`);
        const dom = require("../lib/dom");
        dom.importCssString(exports.cssText, exports.cssClass, !1)
      });
      (function () {
        window.require(["ace/theme/" + name], function (m) {
          if (typeof module == "object" && typeof exports == "object" && module) {
            module.exports = m;
          }
        });
      })();
      
      
      if (currentTheme === name) 
        editor.setTheme("ace/theme/" + name);
    })
    
    settings.on("update", this.onThemeChange)
  }
  
  async destroy() { settings.off("update", this.onThemeChange) }
  
  onThemeChange(value) {
    const changedTheme = value.split("/").pop()
    if (themes.includes(changedTheme)) {
      editor.setTheme("ace/theme/" + changedTheme)
      settings.update({ editorTheme: changedTheme })
    }
  }
}

if (window.acode) {
  const acodePlugin = new AcodePlugin();
  acode.setPluginInit(plugin.id, (baseUrl, $page, { cacheFileUrl, cacheFile }) => {
    if (!baseUrl.endsWith('/')) {
      baseUrl += '/';
    }
    acodePlugin.baseUrl = baseUrl;
    acodePlugin.init($page, cacheFile, cacheFileUrl);
  });
  acode.setPluginUnmount(plugin.id, () => {
    acodePlugin.destroy();
  });
} 
```

try it

**Comment by sebastianjnuwu** [comment]
> 

```js
if (currentTheme === name) 
      editor.setTheme("ace/theme/" + name);
 });

settings.on("update", this.onThemeChange)
```
  Is it even outside the if? It will not loop

**Comment by legend-sabbir** [comment]
bruh it is working . just use it as it is if you dont understand

**Comment by sebastianjnuwu** [comment]
It's almost all working right the error that when closing and opening the acode was solved.

I found another bug and in the editor's list (I don't know if it's just me) when I close and open the app I go to the editor's themes no selected theme appears but my theme is still active

**Comment by legend-sabbir** [comment]
I know that this problem exists . Currently no way to fix . It is because there is no api in acode to add editor theme . I just did tricky solution and this is the drawback

**Comment by sebastianjnuwu** [comment]
Ok thanks for solving my problem 💜
